'use strict';
const test=require('node:test'),assert=require('node:assert/strict');
const {POWERTEACHER_STAGE2_UI_CONTRACT}=require('../../extension/src/platform/powerteacher/teacher-ui-contract.js');
const {readTeacherUiState}=require('../../extension/src/platform/powerteacher/teacher-ui-adapter.js');
const STRANDS=['MS1-Academic','MS1-Attitude','MS1-Behaviour','MS1-Classwork','MS1-Communication','MS1-Collaboratively','MS1-Creativity','MS1-Equipment'];
function el({text='',value='',visible=true,active=false}={}){const parent=active?{classList:{contains:n=>n==='active'},parentElement:null}:null;return{textContent:text,value,parentElement:parent,isConnected:true,getClientRects:()=>visible?[{}]:[]};}
function doc(markerTexts=[]){const map=new Map([['#sidebar-charms-grading',el({text:'GRADING',active:true})],['#section-mega-menu',el({text:'STANDARDS'})],['#standard-final-grades',el()],['#simple-search-standard-final-grades',el({value:'MS1'})],['.course-name',el({text:'2L8I Science (Khoa học)'})]]);map.get('#standard-final-grades').querySelectorAll=()=>markerTexts.map(text=>el({text}));return{location:{origin:'https://vas.powerschool.com',pathname:'/teachers/index.html'},body:{isConnected:true},defaultView:{getComputedStyle:e=>({display:e.getClientRects().length?'block':'none',visibility:'visible',opacity:'1'})},querySelector:s=>map.get(s)||null,querySelectorAll:s=>map.has(s)?[map.get(s)]:[]};}
test('all eight visible MS1 strand identifiers verify the rubric even with TA columns present',()=>{const state=readTeacherUiState(doc(['MS1-TA-Grade.CAPI.G02.CSCI','MS1-VN-Ranking.CAPI.G02.CSCI',...STRANDS]),POWERTEACHER_STAGE2_UI_CONTRACT);assert.equal(state.workflowMarkerPresent,true);assert.equal(state.workflowMarkerKey,'ms1-strands');assert.deepEqual(state.workflowMarkerEvidence,STRANDS);assert.equal(state.courseLabel,'2L8I Science (Khoa học)');});
test('TA Grade and Ranking alone are not the eight-category MS1 rubric',()=>{const state=readTeacherUiState(doc(['MS1-TA-Grade.CAPI.G02.CSCI','MS1-VN-Ranking.CAPI.G02.CSCI']),POWERTEACHER_STAGE2_UI_CONTRACT);assert.equal(state.workflowMarkerPresent,false);assert.equal(state.workflowMarkerKey,null);assert.deepEqual(state.workflowMarkerEvidence,[]);});
test('partial MS1 strand set fails closed',()=>{const state=readTeacherUiState(doc(STRANDS.slice(0,7)),POWERTEACHER_STAGE2_UI_CONTRACT);assert.equal(state.workflowMarkerPresent,'unknown');assert.ok(state.reasonCodes.includes('workflow-marker-incomplete'));});
